# First, we will name this workflow:

name: ci

# Then, we will choose when we run this workflow.
# We are going to do it for every push against the main branch of our project:

on:
  push:
    branches:
      - 'main'

# Specify what we actually want to happen within our workflow (what jobs), 
# select that it runs on the latest Ubuntu instances available
jobs:
  build:
    runs-on: ubuntu-latest

# Add the steps required:
# - The first one checks-out our repository under $GITHUB_WORKSPACE, so our workflow can access it.
# - The second one will use our PAT and username to log into Docker Hub.
# - The third will setup Docker Buildx to create the builder instance using a BuildKit container under the hood.
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/metamex:latest
          
          
